name: Trigger Jira on Branch Create

on:
  create:
    branches:
      - '*'

jobs:
  trigger-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook to Jira
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Automation-Webhook-Token: ${{ secrets.JIRA_WEBHOOK_TOKEN }}" \
            -d '${{ toJson(github.event) }}' \
            "https://api-private.atlassian.com/automation/webhooks/jira/a/3e3010d6-8973-4ecb-b7cd-d50a4731f45b/019c967f-91fd-7489-a6da-7e3fd8affc57"
